### ISSUE TITLE
Actualización de RoadMap

### ISSUE THREAD

**Issue by milo19980525** [udistrital/sga_cliente#1263]
Teniendo en cuenta la inducción realizada con Juan Pablo [inducción](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/cerochac_udistrital_edu_co/Documents/Trabajo%20OAS/2023/Resoluciones%20V2?csf=1&web=1&e=hOOUlw), bajar cada uno de los repositorios asociados al sistema de resoluciones v2 (Cliente, mid y crud) y montarlos en un ambiente local, para comprender la parametrización de fechas de resoluciones y su interacción con titan y Argo.

**Especificaciones técnicas**

- Clonar los repositorios de resoluciones v2 en local.
- Determinar el manejo actual de fechas de resoluciones de vinculación, adición, reducción y cancelación.
- Establecer correlación de datos con apis de titan y Agora o Argo.

**Sub Tareas**

- [ ] Clonar los repositorios.
- [ ] Parametrizar en un comentario del issue como se están tratando las fechas en las resoluciones de cada tipo (vinculación, adición, reducción y cancelación)
- [ ] Definir si se manejan las fechas de igual manera en Argo/Agora, resoluciones v2 y titán.

**Criterios de aceptación**

- [ ] Comentario del issue con la parametrización de fechas de todos los tipos de resoluciones.
- [ ] Comentario del issue que relacione como se manejan las fechas en Argo/Agora y titán.
- [ ] En dado caso de tener diferencia de manejo de fechas entre los sistemas colocar los respectivos comentarios. 

**Requerimientos**

- [ ] Ninguna

**Dependencias**

- Argo
- Agora
- Titán

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [ ] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] Las dependencias entán identificadas y resueltas.
- [ ] Puede ser probada dentro del Sprint.

**Comment by fabianbarreto02** [comment]
Se realiza la actualización del roadmap para los hitos 2,3 y 4 según requerimientos solicitados, en resumen se estableció el siguiente roadmap:

1. Hito 2  Modulo de espacios academicos y submodulo de planes de estudios

- Features: Diseño y definición de mockups, Implementación componentes para el modulo de espacios académicos y planes de estudio, Diseño e implementación del modelo de datos y api crud para los módulos de espacios académicos y planes de estudio, Implementación de funcionalidad transicional a nivel de mid para las funcionalidad de creación, edición, consulta y eliminación de espacios académicos y planes de estudio, Creación de reportes para los planes de estudios registrados en el sistema SGA y Entrega del modulo y despliegue del modulo en entorno de producción.


2. Hito 3 Modulo de Gestión Plan de Trabajo Docente y submódulo Modulo para la carga electiva docente

- Features: Implementación componentes para el modulo de gestión plan de trabajo docente, Diseño e implementación del modelo de datos y api crud para el modulo de gestión plan de trabajo docente, Implementación de funcionalidad transicional a nivel de mid para las funcionalidad de creación, edición, consulta y eliminación del modulo de carga lectiva, Implementación de funcionalidad transicional a nivel de mid para las funcionalidad de creación, edición, consulta y eliminación del modulo de carga de actividades, Implementación funcionalidad validación plan de trabajo docente e implementación de flujo de estado del proceso entre coordinación y docente, Implementación de funcionalidad validación plan de trabajo docente, flujo de estados del proceso entre coordinación y  decanatura, Implementación de reportes para el proceso de plan trabajo docente 

3.   Hito 4 Modulo para la creación de horario

- Features: Diseño y creación de mockups para la generación de horarios del sistema SGA, Implementación de componente para la generación de horarios del sistema SGA, Implementación de generación de horarios para el sistema SGA, Implementación de generación de reportes de horarios para el sistema SGA


En el documento de excel [roadmap-Poyectos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=MlLdiA) se encuentra toda la documentación.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
