### ISSUE TITLE
Generación del roadmap para la próxima contratación del sistema SISGPLAN 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1268]
Se requiere realizar la generación del roadmap para la próxima contratación del sistema SISGPLAN: 

**Sub Tareas**

- [ ] Generación de la ruta de trabajo para la siguiente contratación del sistema SISGPLAN con una duración de 8 meses y un recurso.
- [ ] Creación de Hitos, Features, Work Items (HUs - Issues), Fases y Story Points para la ruta definida.
- [ ] Agrupar las actividades y subactividades en milestones o sprints teniendo en cuenta la disponibilidad del equipo. 

**Criterios de aceptación**

- [ ] Comentario en issue que proporcione un resumen de las actividades agregadas al roadmap diariamente.
- [ ]  Actualización de actividades en el roadmap.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Se realiza la actualización del roadmap para los nueve hitos  según requerimientos solicitados, en resumen se estableció el siguiente roadmap:

1. Hito 1: Modulo de construcción versión dos

- Features: Diseño de discriminación de asignación de fechas particulares a unidades particulares, Implementación backend de discriminación de asignación de fechas particulares a unidades particulares, Implementación cliente de discriminación de asignación de fechas particulares a unidades particulares, Diseño de asignación de rol y unidad para el ingreso al sistema, Implementación backend funcionalidad de asignación de rol y unidad para el ingreso al sistema, Implementación cliente funcionalidad de asignación de rol y unidad para el ingreso al sistema, sub Modulo de verificación, consulta y actualización de correos para notificación dentro del sistema, Sub modulo de generación de tirillas y notificaciones en el sistema 

2. Hito 2: Módulo de Plan de Acción versión dos

-   Features: Creación de tabla general de resumen para el rol de planeación modulo de formulación de planes de acción de funcionamiento, Creación funcionalidad para notificación interna de observaciones en el plan de acción de funcionamiento, Verficiación y ajuste del componente identificación docente, Inclusión de nuevo estado para la pre aval entre jefe de depencia y asistente de dependencia para los proceso de formualción y seguimiento a los planes de acción de funcionamientos y Ajuste de flujo de bloqueo de acciones con el flujo de estados.

3. Hito 3: Submódulo Evaluación versión dos

-  Features: Ajuste para el modulo de generación de evaluaciones a planes de acción de funcionamiento  y Implementación  del semáforo para el proceso de evaluación a los planes de acción de funcionamiento

4. Hito 4: Submódulo Generación de Reportes

- Features: Ajuste de generación de reportes independiente del estado del plan y Creación de reportes interactivos en el sistema para los planes de acción de funcionamiento

5. Hito 5: Restructuración de flujo de estados en el sistema para el proceso de formulación y seguimiento para planes de acción de funcionamiento

- Features: Restructuración de flujo de estados en el sistema para el proceso de formulación y seguimiento para planes de acción de funcionamiento

6. Hito 6: Modulo de notificación automática para las distintas acciones del proceso de formulación y seguimiento a planes de acción

- Features: Análisis de requerimientos para la implementación de notificaciones automáticas, Submódulo para la definición de templete de mensajes de notificación, Implementación a nivel backend para la implementación de notificaciones por correo en el sistema SISGPLAN y Implementación de flujo para la implementación de notificaciones por correo en el sistema SISGPLAN

7. Hito 7: Modulo para solicitud de ajuste a planes de acción de funcionamiento avalados 

- Features: Definición de requerimientos para el modulo de solicitud de ajustes, Implementación a nivel de backend para el modulo de solicitud de ajustes y Implementación a nivel de cliente para el modulo de solicitud de ajustes

8. Hito 8: Seguimiento a plan  estratégico 

- Features: Diseño y definición de modelos de datos para el seguimiento a plan estratégico, Funcionalidad a nivel de backend para el seguimiento a plan estrategico y Funcionalidad a nivel de cliente para el seguimiento a plan estrategico

9. Hito 9: Seguimiento a Plan Indicativo 

- Features: Diseño y definición de midelos de datos para el seguimiento a Plan Indicativo, Funcionalidad a nivel de backend para el seguimiento a Plan Indicativo  y Funcionalidad a nivel de cliente para el seguimiento a Plan Indicativo 


La documentación de la issue se encuentra en el siguiente excel  https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EepZLJs3LZVOlbwvOwUdxu4B01zKTTIlrUJ-c2yGTs6PAA?e=wstI6q
