### ISSUE TITLE
Generación de subactividades para el hito 3 del roadmap del sistema de SGA

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1269]
Se requiere realizar la Generación de subactividades para el hito 3 del roadmap del sistema de SGA

**Sub Tareas**

- [x] Creación de subactividades para cada Work Items (HUs - Issues) definido en el roadmap de SGA
- [x] Documentar en el excel las actividades 

**Criterios de aceptación**

- [x] Documentación en el excel del roadmap del sistema SGA

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
