### ISSUE TITLE
Generación del roadmap para la próxima contratación del sistema SISGPLAN proceso banco de proyectos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1285]
Se requiere realizar el 

- [ ] Generación de la ruta de trabajo para la siguiente contratación del sistema SISGPLAN con una duración de 8 meses y un recurso para el proceso banco de proyectos.
- [x  Creación de Hitos, Features, Work Items (HUs - Issues), Fases y Story Points para la ruta definida.
- [ ] Agrupar las actividades y subactividades en milestones o sprints teniendo en cuenta la disponibilidad del equipo. 

**Criterios de aceptación**

- [ ] Comentario en issue que proporcione un resumen de las actividades agregadas al roadmap diariamente.
- [ ]  Actualización de actividades en el roadmap.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Se realiza la actualización del roadmap para los nueve hitos según requerimientos solicitados, en resumen se estableció el siguiente roadmap:

1. Hito 1: Ajustes al modulo de formulación a planes de acción de inversión

- Features: Ajuste de bugs  para el modulo de fuentes de financiamiento, proyectos de inversión y formulación de planes de acción de inversión, Ajustes de forma y flujo al modulo de inversión.

2. Hito 2: Modulo de seguimiento a los planes de acción de inversión

- Features: Analisis de modelo de datos para el seguimiento a los planes de acción de inversión, Creación de controlador para funcionalidad crud para el seguimiento a los planes de acción de inversión, Creación de componentes para el proceso de seguimiento a los planes de acción de inversión, Implementación de funcionalidad en el cliente para el proceso de  seguimiento a los planes de acción de inversión, Implementación de flujo de estado y observación para el proceso de seguimiento a los planes de acción de inversión, Implementación de funcionalidad de semaforo para el proceso seguimiento a los planes de acción de inversión y Despliegue de modulo en entorno de producción 

3. Hito 3: Modulo de evaluación para el proceso  seguimiento a los planes de acción de inversión

- Features: Implementación de controladores para el proceso de evalucion de  seguimiento a los planes de acción de inversión, Implementación de componente para la evaluación del proceso seguimiento a los planes de acción de inversión y Implementación de visualización dinamica de evaluación para el proceso seguimiento a los planes de acción de inversión

4. Hito 4: Generación de reportes para el proceso de seguimiento a los planes de acción de inversión

- Features: Implementación de funcionalidad para la consulta de reportes para el proceso seguimiento a los planes de acción de inversión, Implementación de componentes para la consulta de reportes para el proceso seguimiento a los planes de acción de inversión, Generación de reporte en excel para el proceso de reporte para los segumiento a los planes de acción de funcionamiento, Despliegue de modulo en entorno de producción 

5. Hito 5: Planeación de la programación presupuestal primer versión

- Features: Analisis de modelo de datos para la Planeación de la programación presupuestal primer versión, Implementación de funcionalidad backend para el proceso de Planeación de la programación presupuestal primer versión y Implementación de funcionalidad cliente para el proceso de Planeación de la programación presupuestal primer versión

La documentación de la issue se encuentra en el siguiente excel  https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXB3fgRRB1REqWrWpUflhX8BYf30D_6YG4QaBC-wUjKK2g?e=GoOlv6
