### ISSUE TITLE
Creación del roadmap para la la implementación del hito syllabus 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1393]
Se requiere realizar el Creación del roadmap para la la implementación del hito syllabus 

**Sub Tareas**

- [x] Creación del roadmap
- [x] Estimación de punto de historia para las actividades definidas en el roadmap
- [x] Creación de las descripción de las actividades definidas con su respectiva issue

**Criterios de aceptación**

- [x] Documentación en el archivo de roasmap_proyectos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Se realiza la creación de la issue y la documentación en el roadmap disponible en 

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=HJiKaw
